-- Bai thuc hanh 4

-- Cau 1
SELECT * FROM NHANVIEN WHERE PHG = 4;

-- Cau 2
SELECT * FROM NHANVIEN WHERE LUONG > 30000

-- Cau 3
SELECT * FROM NHANVIEN WHERE (LUONG > 25000 AND PHG = 4) OR (LUONG > 30000 AND PHG = 5)

-- Cau 4
SELECT HONV + TENLOT + TENNV AS FULLNAME FROM NHANVIEN WHERE DCHI LIKE '%TP HCM%'

-- Cau 5
SELECT HONV + TENLOT + TENNV AS FULLNAME FROM NHANVIEN WHERE HONV LIKE 'N%'

-- Cau 6
SELECT NGSINH, DCHI FROM NHANVIEN WHERE HONV = 'Dinh' AND TENLOT = 'Ba' AND TENNV = 'Tien'

-- Cau 7
SELECT * FROM NHANVIEN WHERE YEAR(NGSINH) BETWEEN 1960 AND 1965

-- Cau 8
SELECT *, YEAR(NGSINH) AS NAMSINH FROM NHANVIEN

-- Cau 9
SELECT *, YEAR(GETDATE()) - YEAR(NGSINH) AS TUOI FROM NHANVIEN